services:
  - type: web
    name: sih-portal
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@codersclub.edu.in
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL_2
        value: asmaeram006@gmail.com
      - key: ADMIN_PASSWORD_2
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: codersclub@gprec.ac.in
      - key: SENDGRID_FROM_NAME
        value: Coders Club & CIE SIH Portal
      - key: WHATSAPP_GROUP_LINK
        value: https://chat.whatsapp.com/EIoDz1GewoZLVXYJEdfR0t?s=sw&p=a&mlu=4&ilr=4
      - key: LIVE_SPREADSHEET_URL
        value: https://docs.google.com/spreadsheets/d/1LHSq7l3zEeAtCKd8ZfqyDA7RJFcyMR541cljhQClUGY/edit?usp=sharing
      - key: GOOGLE_SHEET_WEBHOOK_URL
        sync: false
